services:
  - type: web
    name: interview-prep-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: interview-prep-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: header
        source: /*
        headers:
          - key: Cross-Origin-Opener-Policy
            value: same-origin-allow-popups
          - key: Cross-Origin-Embedder-Policy
            value: unsafe-none
      - type: rewrite
        source: /*
        destination: /index.html
